{
 "title": "Storage Work Group Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   {
    "name": "nodename",
    "label": "nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, nodename)"
    }
   },
   { "name": "storage_jason", "query": "marcusolsson-json-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Bucket list",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "queryText": "query {\n  data:storageBuckets {\n    id\n    acceptingNewBags\n    dataObjectCountLimit\n    dataObjectsSizeLimit\n    dataObjectsCount\n    dataObjectsSize\n    operatorMetadata {\n      nodeEndpoint\n      nodeLocation {\n        city\n        countryCode\n      }\n    }\n  }\n}\n",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Nodes locations",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "queryText": "query {\n data:storageBuckets {\n    acceptingNewBags\n    id\n    operatorMetadata {\n      nodeLocation {\n        coordinates {\n          latitude\n          longitude\n        }\n        city\n        countryCode\n      }\n}}}"
    }
   ]
  },
  {
   "title": "Worker list",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "queryText": "query {\ndata:workers(\n    where: { group: { id_eq: \"storageWorkingGroup\" }, isActive_eq: true }) {\n   workerId:runtimeId\n   membership {\n   id\n   handle\n   }\n   rewardPerBlock\n   rewardAccount\n   }\n   }",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Storage Status - Capacity(Size)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize", "language": "jsonata", "name": "Bytes", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize", "language": "jsonpath", "name": "Bytes", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize", "language": "jsonpath", "name": "Bytes", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize", "language": "jsonpath", "name": "Bytes", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize", "language": "jsonpath", "name": "Bytes", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize", "language": "jsonpath", "name": "Bytes", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/"
    }
   ]
  },
  {
   "title": "Storage Status - Number of Objects",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "language": "jsonata", "name": "Number of Objects" }
     ],
     "method": "GET",
     "urlPath": "/"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": "Number of Objects" }
     ],
     "method": "GET",
     "urlPath": "/"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": "Number of Objects" }
     ],
     "method": "GET",
     "urlPath": "/"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": "Number of Objects" }
     ],
     "method": "GET",
     "urlPath": "/"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": "Number of Objects" }
     ],
     "method": "GET",
     "urlPath": "/"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": "Number of Objects" }
     ],
     "method": "GET",
     "urlPath": "/"
    }
   ]
  },
  {
   "title": "Basic CPU / Mem / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System-0xbc"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System-bewarelabs"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System-coin-side"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System-freakstatic"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System-kalpakci"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System-YYAGI"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - 0x2bc"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - bewarelabs"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - coin-side"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - freakstatic"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - kalpakci"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - YYAGI"
    }
   ]
  },
  {
   "title": "Filesystem space available",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - Available- 0x2bc"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - Available- bewarelabs"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - Available- coin-side"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - Available- freakstatic"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - Available- kalpakci"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - Available- YYAGI"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - 0x2bc"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - bewarelabs"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - coin-side"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - freakstatic"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - kalpakci"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - YYAGI"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - 0x2bc"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} - 0x2bc"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - bewarelabs"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}- bewarelabs"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - coin-side"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}- coin-side"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - freakstatic"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}-  freakstatic"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - kalpakci"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}-  kalpakci"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - YYAGI"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}-  YYAGI"
    }
   ]
  }
 ]
}