version: '3.6'
services:
  packetbeat:
    image: docker.elastic.co/beats/packetbeat:8.2.3
    container_name: packetbeat
    cap_add: ['NET_RAW', 'NET_ADMIN']
    network_mode: host
    user: root
    command: -e -E 'output.elasticsearch.hosts=["https://elastic.joystreamstats.live:443"]'
    command: --strict.perms=false -e -E output.elasticsearch.hosts="https://elastic.joystreamstats.live:443" # -e flag to log to stderr and disable syslog/file output
    secrets:
      - source: packetbeat.yml
        target: /usr/share/packetbeat/packetbeat.yml
    healthcheck:
      test: packetbeat test config
      interval: 30s
      timeout: 15s
      retries: 5
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.2.3
    container_name: metricbeat
    network_mode: host
    user: root
    command: --strict.perms=false -system.hostfs=/hostfs -e -E output.elasticsearch.hosts="https://elastic.joystreamstats.live:443" # -e flag to log to stderr and disable syslog/file output
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    secrets:
      - source: metricbeat.yml
        target: /usr/share/metricbeat/metricbeat.yml
    healthcheck:
      test: metricbeat test config
      interval: 30s
      timeout: 15s
      retries: 5
secrets:  
  packetbeat.yml:
    file: ./config/packetbeat/packetbeat.yml
  metricbeat.yml:
    file: ./config/metricbeat/metricbeat.yml
