{
 "title": "Storage Work Group Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   {
    "name": "nodename",
    "label": "nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, nodename)"
    }
   },
   { "name": "storage_jason", "query": "marcusolsson-json-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Nodes locations",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "queryText": "query {\n data:storageBuckets {\n    acceptingNewBags\n    id\n    operatorMetadata {\n      nodeLocation {\n        coordinates {\n          latitude\n          longitude\n        }\n        city\n        countryCode\n      }\n}}}"
    }
   ]
  },
  {
   "title": "Worker list",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "queryText": "query {\ndata:workers(\n    where: { group: { id_eq: \"storageWorkingGroup\" }, isActive_eq: true }) {\n   workerId:runtimeId\n   membership {\n   id\n   handle\n   }\n   rewardPerBlock\n   rewardAccount\n   }\n   }",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Bucket list",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "queryText": "query {\n  data:storageBuckets {\n    id\n    operatorStatus {\n      ... on StorageBucketOperatorStatusActive {\n        workerId\n      }\n    }\n    acceptingNewBags\n    dataObjectCountLimit\n    dataObjectsSizeLimit\n    dataObjectsCount\n    dataObjectsSize\n    operatorMetadata {\n      nodeEndpoint\n      nodeLocation {\n        city\n        countryCode\n      }\n    }\n\n  }\n\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Storage Status - Version",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "version", "language": "jsonata", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/version"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "version", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/version"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "version", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/version"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "version", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/version"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "version", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/version"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "version", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/version"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "version", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/version"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "version", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/version"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "version", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/version"
    }
   ]
  },
  {
   "title": "Storage Status - QN URL",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "queryNodeStatus.url", "name": "  " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "queryNodeStatus.url", "name": "  " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "queryNodeStatus.url", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "queryNodeStatus.url", "name": "  " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "queryNodeStatus.url", "name": " ", "type": "string" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "queryNodeStatus.url", "name": " ", "type": "string" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "queryNodeStatus.url", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "queryNodeStatus.url", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "queryNodeStatus.url", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    }
   ]
  },
  {
   "title": "Storage Status - Node - Capacity(Size TB)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize + tempDirSize", "language": "jsonata", "name": " ", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize + tempDirSize", "language": "jsonata", "name": " ", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize + tempDirSize", "language": "jsonata", "name": " ", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize + tempDirSize", "language": "jsonata", "name": "  ", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize + tempDirSize", "language": "jsonata", "name": " ", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize + tempDirSize", "language": "jsonata", "name": " ", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize + tempDirSize", "language": "jsonata", "name": " ", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize + tempDirSize", "language": "jsonata", "name": " ", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize + tempDirSize", "language": "jsonata", "name": " ", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    }
   ]
  },
  {
   "title": "Storage Status - Node - Number of Objects",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "language": "jsonata", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    }
   ]
  },
  {
   "title": "Storage Status - QN Block Processed",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "queryNodeStatus.chainHead", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "queryNodeStatus.blocksProcessed",
       "name": " "
      }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "queryNodeStatus.blocksProcessed",
       "name": " "
      }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "queryNodeStatus.blocksProcessed",
       "name": " "
      }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "queryNodeStatus.blocksProcessed",
       "name": " "
      }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "queryNodeStatus.blocksProcessed",
       "name": " "
      }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "queryNodeStatus.blocksProcessed",
       "name": " "
      }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "queryNodeStatus.blocksProcessed",
       "language": "jsonpath",
       "name": " "
      }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "queryNodeStatus.blocksProcessed",
       "language": "jsonpath",
       "name": " "
      }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "queryNodeStatus.blocksProcessed",
       "language": "jsonpath",
       "name": " "
      }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    }
   ]
  },
  {
   "title": "Basic CPU / Mem / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System-0xbc"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System-bewarelabs"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System-freakstatic"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System-kalpakci"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System-YYAGI"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System-iTor"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System-siemma"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System-tomato"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System-jonnyboy"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - 0x2bc"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - bewarelabs"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - freakstatic"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - kalpakci"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - YYAGI"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - iTor"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - siemma"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - tomato"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - jonnyboy"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - 0x2bc"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} - 0x2bc"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - bewarelabs"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}- bewarelabs"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - freakstatic"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}-  freakstatic"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - kalpakci"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}-  kalpakci"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - YYAGI"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}-  YYAGI"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - iTor"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}-  iTor"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}-  siemma"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - siemma"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}-  tmato"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}-  jonnyboy"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - tomato"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - jonnyboy"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - 0x2bc"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - bewarelabs"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - freakstatic"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - kalpakci"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - YYAGI"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - iTor"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - siemma"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - tomato"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - jonnyboy"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 29, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} - node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - 0x2bc"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} - node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - bewarelabs"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} - node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - freakstatic"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} - node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - iTor"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} - node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - kalpakci"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} - node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - YYAGI"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} - node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - siemma"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} - node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - tomato"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} - node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - jonny"
    }
   ]
  },
  {
   "title": "Filesystem space available",
   "type": "timeseries",
   "gridPos": { "h": 29, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - 0x2bc"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - bewarelabs"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - freakstatic"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - kalpakci"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - YYAGI"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - iTor"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - siemma"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - tomato"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - jonnyboy"
    }
   ]
  },
  {
   "title": "Global Averages Response Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 141 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      {
       "id": "1",
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "fields.meta.res.statusCode: 200",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 149 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "logs"
      }
     ],
     "query": "severity: error NOT message: \"^Sync.*\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}