{
 "title": "Storage Work Group Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   {
    "name": "nodename",
    "label": "nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, nodename)"
    }
   },
   { "name": "storage_jason", "query": "marcusolsson-json-datasource" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Nodes locations",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "queryText": "query {\n data:storageBuckets(orderBy: createdAt_ASC) {\n    acceptingNewBags\n    id\n    operatorMetadata {\n      nodeLocation {\n        coordinates {\n          latitude\n          longitude\n        }\n        city\n        countryCode\n      }\n}}}"
    }
   ]
  },
  {
   "title": "Worker list",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "queryText": "query {\ndata:workers(\n    where: { group: { id_eq: \"storageWorkingGroup\" }, isActive_eq: true }) {\n   workerId:runtimeId\n   membership {\n   id\n   handle\n   }\n   rewardPerBlock\n   rewardAccount\n   }\n   }",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Bucket list",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "queryText": "query {\n  data:storageBuckets(orderBy: createdAt_ASC) {\n    id\n    operatorStatus {\n      ... on StorageBucketOperatorStatusActive {\n        workerId\n      }\n    }\n    acceptingNewBags\n    dataObjectCountLimit\n    dataObjectsSizeLimit\n    dataObjectsCount\n    dataObjectsSize\n    operatorMetadata {\n      nodeEndpoint\n      nodeLocation {\n        city\n        countryCode\n      }\n    }\n\n  }\n\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Storage Status - Version",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "version", "language": "jsonata", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/version"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "version", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/version"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "version", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/version"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "version", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/version"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "version", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/version"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "version", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/version"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "version", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/version"
    }
   ]
  },
  {
   "title": "Storage Status - QN URL",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "queryNodeStatus.url", "name": "  " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "queryNodeStatus.url", "name": " ", "type": "string" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "queryNodeStatus.url", "name": " ", "type": "string" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "queryNodeStatus.url", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "queryNodeStatus.url", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "queryNodeStatus.url", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "queryNodeStatus.url", "language": "jsonpath", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    }
   ]
  },
  {
   "title": "Capacity Usage per Node - QN",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "queryText": "query {\n  data:storageBuckets {\n    id\n    dataObjectsSize\n    dataObjectsSizeLimit\n  }\n\n}"
    }
   ]
  },
  {
   "title": "Total Capacity - QN",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "queryText": "query {\n  data:storageBuckets {\n    dataObjectsSize\n    dataObjectsSizeLimit\n  }\n\n}"
    }
   ]
  },
  {
   "title": "Storage Used - Node",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "storage_node_totalSize+storage_node_tempDirSize",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(storage_node_totalSize)+sum(storage_node_tempDirSize)",
     "legendFormat": "Total Storage"
    }
   ]
  },
  {
   "title": "Storage Status - Node - Capacity(Size TB)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize + tempDirSize", "language": "jsonata", "name": " ", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize + tempDirSize", "language": "jsonata", "name": "  ", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize + tempDirSize", "language": "jsonata", "name": " ", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize + tempDirSize", "language": "jsonata", "name": " ", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize + tempDirSize", "language": "jsonata", "name": " ", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize + tempDirSize", "language": "jsonata", "name": " ", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "totalSize + tempDirSize", "language": "jsonata", "name": " ", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    }
   ]
  },
  {
   "title": "Storage Status - Node - Number of Objects",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "language": "jsonata", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "objectNumber", "name": " " }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/state/data"
    }
   ]
  },
  {
   "title": "Storage Status - QN Block Processed",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "queryNodeStatus.blocksProcessed",
       "name": " "
      }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "queryNodeStatus.blocksProcessed",
       "name": " "
      }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "queryNodeStatus.blocksProcessed",
       "name": " "
      }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "queryNodeStatus.blocksProcessed",
       "language": "jsonpath",
       "name": " "
      }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "queryNodeStatus.blocksProcessed",
       "language": "jsonpath",
       "name": " "
      }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "queryNodeStatus.blocksProcessed",
       "language": "jsonpath",
       "name": " "
      }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "queryNodeStatus.blocksProcessed",
       "language": "jsonpath",
       "name": " "
      }
     ],
     "method": "GET",
     "urlPath": "/storage/api/v1/status"
    }
   ]
  },
  {
   "title": "Basic CPU / Mem / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval]))) * 100",
     "legendFormat": "Busy System-0xbc"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval]))) * 100",
     "legendFormat": "Busy System-kalpakci"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval]))) * 100",
     "legendFormat": "Busy System-YYAGI"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval]))) * 100",
     "legendFormat": "Busy System-sieemma2"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval]))) * 100",
     "legendFormat": "Busy System-siemma"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval]))) * 100",
     "legendFormat": "Busy System-mmx2"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System-mrbovo"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System-mmx"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - 0x2bc"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - kalpakci"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - YYAGI"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - sieema2"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - siemma"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - mmx2"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - mrbovo"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used - mmx"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - 0x2bc"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} - 0x2bc"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - kalpakci"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}-  kalpakci"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - YYAGI"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}-  YYAGI"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - sieemma2"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}-  andybut"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}-  siemma"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - siemma"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - mmx2"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}-   mmx2"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "recv {{device}} - mrbovo"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}-   mrbovo"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'lo.*|docker.*|br.*|veth.*'}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}-   mmx"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'})",
     "legendFormat": "{{mountpoint}} - 0x2bc"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - kalpakci"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - YYAGI"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - sieemma2"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'})",
     "legendFormat": "{{mountpoint}} - siemma"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'})",
     "legendFormat": "{{mountpoint}} - mmx2"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'})",
     "legendFormat": "{{mountpoint}} - mrbovo"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'})",
     "legendFormat": "{{mountpoint}} - mmx"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 42, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'} - node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'}",
     "legendFormat": "{{mountpoint}} - 0x2bc"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} - node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - sieemma2"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} - node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - kalpakci"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'} - node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - YYAGI"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*',mountpoint!~'/run.*'} - node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*',mountpoint!~'/run.*'}",
     "legendFormat": "{{mountpoint}} - siemma"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'} - node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'}",
     "legendFormat": "{{mountpoint}} - mmx2"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'} - node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'}",
     "legendFormat": "{{mountpoint}} - mrbovo"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'} - node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'}",
     "legendFormat": "{{mountpoint}} - mmx"
    }
   ]
  },
  {
   "title": "Filesystem space available",
   "type": "timeseries",
   "gridPos": { "h": 42, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'}",
     "legendFormat": "{{mountpoint}} - 0x2bc"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - kalpakci"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - YYAGI"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*'}",
     "legendFormat": "{{mountpoint}} - sieemma2"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*',mountpoint!~'/run.*'}",
     "legendFormat": "{{mountpoint}} - siemma"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'}",
     "legendFormat": "{{mountpoint}} - mmx2"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'}",
     "legendFormat": "{{mountpoint}} - mrbovo"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~'tmpfs',mountpoint!~'/boot.*|/run.*'}",
     "legendFormat": "{{mountpoint}} - mmx"
    }
   ]
  },
  {
   "title": "Upload Per Storage Node",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 170 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "fields.meta.req.method: \"POST\" and fields.meta.req.url: \"/api/v1/files*\" and fields.meta.res.statusCode: 201",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Upload Size Per Storage Node",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 178 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "fields.meta.req.method: \"POST\" and fields.meta.req.url: \"/api/v1/files*\" and fields.meta.res.statusCode: 201",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Upload Source Country",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 186 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "geo.country_name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "fields.meta.req.method: \"POST\" and fields.meta.req.url: \"/api/v1/files*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Upload Per IP address",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 198 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "fields.meta.req.headers.x-forwarded-for",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": " fields.meta.req.method: \"POST\" and fields.meta.req.url: \"/api/v1/files*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Download Source Country",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 206 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "geo.country_name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "fields.meta.req.url: /api/v1/files/* AND fields.meta.req.method: \"GET\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Global Averages Response Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 214 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "fields.meta.res.statusCode : 200",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Global HTTP Upload Response",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 222 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "fields.meta.res.statusCode",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "fields.meta.req.method: POST",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Global HTTP Download Response",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 230 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "fields.meta.res.statusCode",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "fields.meta.req.method: GET and fields.meta.req.url: \"/api/v1/files*\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}