{
 "title": "Blackbox",
 "description": "Prometheus blackbox exporter metrics.",
 "tags": [
  "Prometheus",
  "blackbox"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "database", "label": "database", "query": "prometheus" },
   {
    "name": "job",
    "query": "label_values(probe_success,job)"
   },
   {
    "name": "targets",
    "label": "targets",
    "query": "label_values(up{job=~'$job'},url)"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Status overview", "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTPS duration",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{url=~'$targets'}",
     "legendFormat": "{{instance}} {{phase}} - http"
    }
   ]
  },
  {
   "title": "Global Probe Duration",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{url=~'$targets'}",
     "legendFormat": "{{ instance}}{{phase}}"
    }
   ]
  },
  {
   "title": "Average Connection time",
   "type": "table",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 49 },
   "targets": [
    { "expr": "probe_http_status_code" },
    {
     "expr": "avg_over_time(probe_success[$__range])*100"
    },
    {
     "expr": "avg_over_time(probe_http_duration_seconds{phase=\"resolve\"}[$__range])"
    },
    {
     "expr": "avg_over_time(probe_http_duration_seconds{phase=\"connect\"}[$__range])"
    },
    {
     "expr": "avg_over_time(probe_http_duration_seconds{phase=\"tls\"}[$__range])"
    },
    {
     "expr": "avg_over_time(probe_http_duration_seconds{phase=\"processing\"}[$__range])"
    },
    {
     "expr": "avg_over_time(probe_http_duration_seconds{phase=\"transfer\"}[$__range])"
    }
   ]
  },
  { "title": "Server status overview", "gridPos": { "h": 26, "w": 24, "x": 0, "y": 75 } }
 ]
}