# Tokenomics + Network Report
This is a report which explains the current state of the Joystream network in numbers. It pulls figures from the chain and tries to provide a basic level of information about the network, tokens and more. 

## 1.0 Basic Information
* Date Range: {dateStart} - {dateEnd}
* Council session #: {councilRound}
* Starting block: {startBlock}
* Block range: {startBlock} - {endBlock}

### 1.1 Block Generation Information
| Property                        | This Session | All Sessions | % Change |
|---------------------------------|--------------|--------------|----------|
| Number of blocks                | {newBlocks}       | {endBlock}   |   {percNewBlocks}       |
| Block generation time (average) | {avgBlockProduction}|              |          |
| Number of nodes (average)       |                     |              |          |

### 1.2 Token + USD Information
| Property       | This Session | All Sessions | % Change |
|----------------|--------------|--------------|----------|
| Token Issuance | {newIssuance}   | {totalIssuance}| {percNewIssuance}|
| Token Burn     | {newTokensBurn} |              |          |
| USD Backing    |                 |              |          |

### 1.3 Membership Information
| Property          | This Session | All Sessions | % Change |
|-------------------|--------------|--------------|----------|
| Number of members |{newMembers}  |{totalMembers}|{percNewMembers}|

## 2.0 Tokenomics
### 2.1 Token generation breakdown
| Property                    | This Session | All Sessions | % Change |
|-----------------------------|--------------|--------------|----------|
| Total Tokens Minted         |{totalMinted}            |              |          |
| Validator Role              |{newValidatorReward}|              |          |
| Storage Role                |{newStorageProviderReward}              |              |          |
| Council Role                |              |              |          |

### 2.2 Mints 
| Property                  | This Session | All Sessions | % Change |
|---------------------------|--------------|--------------|----------|
| Council Mint Total Minted |{newCouncilMinted}|              |          |
| Curator Mint Total Minted |{newCuratorMinted}|              |          |

## 3.0 Council
* Council session #: {councilRound}
* Number of council members: {councilMembers}
* Total number of proposals: {newProposals}
### 3.1 Elections
| Property                    | This Session | All Sessions | % Change |
|-----------------------------|--------------|--------------|----------|
| Total Applicants            |{electionApplicants}      |{electionAvgApplicants}||
| Total Applicant Stake       |{electionApplicantsStakes}|              |          |
| Total Votes                 |{electionVotes}           |              |          |
| Avg Votes per Applicant     |{avgVotePerApplicant}     |              |          |

### 3.2 Proposals
| Proposal Type                           | # of proposals during this session | Total number of proposal type |
|-----------------------------------------|------------------------------------|-------------------------------|
| Text                                    | {newTextProposals}                              |                               |
| Runtime Upgrade                         | {newRuntimeUpgradeProposal}                    |                               |
| Set Election Parameters                 | {newSetElectionParametersProposal}              |                               |
| Spending                                | {newSpendingProposal}                           |                               |
| Set Lead                                | {newSetLeadProposal}                            |                               |
| Set Content Working Group Mint Capacity | {newSetContentWorkingGroupMintCapacityProposal} |                               |
| Evict Storage Provider                  | {newEvictStorageProviderProposal}               |                               |
| Set Validator Count                     | {newSetValidatorCountProposal}                  |                               |
| Set Storage Role Parameters             | {newSetStorageRoleParametersProposal}           |                               |
* Average time for proposal vote success:
* Average overall time for proposal vote success:

## 4 Roles
### 4.1 Validator Information
| Property                    | This Session | All Sessions | % Change |
|-----------------------------|--------------|--------------|----------|
| Number of validators        | {avgValidators}             |              |          |
| Validator total stake       |              |              |          |
| Average stake per validator |              |              |          |
| Tokens generated by validator role |{newValidatorReward}            |              |          |

### 4.2 Storage Role
| Property                | This Session | All Sessions | % Change |
|-------------------------|--------------|--------------|----------|
| Number of storage nodes |              |              |          |
| Content storage size    |              |              |          |
| Total storage stake     |              |              |          |
| Average storage stake   |              |              |          |
| Storage Role Reward (/24h)   |              |              |          |

### 4.3 Curator Role
| Property                | This Session | All Sessions | % Change |
|-------------------------|--------------|--------------|----------|
| Curator roles filled     |              |              |          |


## 5.0 User Generated Content
### 5.1 Media & Uploads
| Property                | This Session | All Sessions | % Change |
|-------------------------|--------------|--------------|----------|
| Number of uploads       | {newMedia}       |{totalMedia} | {percNewMedia} |
| Size of content         | {newUsedSpace} | {totalUsedSpace} | {percNewUsedSpace} |
| Average size of content | {avgNewSizePerContent} |  {totalAvgSizePerContent} | {percAvgSizePerContent}|
| Number of channels      | {newChannels} | {totalChannels} | {percNewChannels} |
| Avg. uploads per channel      |              |              |          |

### 5.2 Forum Activity
| Property          | This Session | All Sessions | % Change |
|-------------------|--------------|--------------|----------|
| Number of threads | {newThreads} |{totalThreads}| {percNewThreads}|
| Number of posts   | {newPosts}   |{totalPosts}  | {percNewPosts}|

## 6 Todo / Ideas
* Video duration
* KPIs
* Unique channels
* Verified channels
* Censored channels
* Forum posts by subcategory
* Total staked across platform
