modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      #valid_http_versions: 
      # - "HTTP/1.1"
      valid_status_codes: []  # Defaults to 2xx
      method: GET
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4" # defaults to "ip6"
#  http_post_2xx:
#    prober: http
#    timeout: 5s
#    http:
#      method: POST
#      headers:
#        Content-Type: application/json
#      body: '{}'
#  http_basic_auth_example:
#    prober: http
#    timeout: 5s
#    http:
#      method: POST
#      headers:
#        Host: "login.example.com"
#      basic_auth:
#        username: "username"
#        password: "mysecret"
  tls_connect:
    prober: tcp
    timeout: 5s
    tcp:
      tls: true
  tcp_connect_example:
    prober: tcp
    timeout: 5s
  imap_starttls:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - expect: "OK.*STARTTLS"
        - send: ". STARTTLS"
        - expect: "OK"
        - starttls: true
        - send: ". capability"
        - expect: "CAPABILITY IMAP4rev1"
