name: "YYAGI2_SP"
tags: ["SP", "YYAGI", "MB"]

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: system
  metricsets:
    - "cpu"
    - "load"
    - "filesystem"
    - "fsstat"
    - "memory"
    - "network"
    - "process"
    - "core"
    - "diskio"
    - "socket"
  period: 5s
  enabled: true
  processes: ['.*']
  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]
  process.cgroups.enabled: false

#metricbeat.modules:
#- module: docker
#  metricsets:
#    - "container"
#    - "cpu"
#    - "diskio"
#    - "healthcheck"
#    - "info"
#    #- "image"
#    - "memory"
#    - "network"
#  hosts: ["unix:///var/run/docker.sock"]
#  period: 10s
#  enabled: true
 
hostfs: "/hostfs"

output.elasticsearch:
  hosts: ["https://elastic.joystreamstats.live:443"]
  protocol: "https"
  pipeline: geoip-info
  #api_key: "MHJ6bVhvRUJybmlHM2NJSC16cmw6OE1CMmdpeXFSaTZjR1B0M3cxeFBfQQ=="
  username: "beats_admin"
  password: "*****"
  # username: beats_system
  # Read PW from packetbeat.keystore
  # password: "*****"
  # ssl.certificate_authorities: ["/usr/share/packetbeat/certs/ca/ca.crt"]

#setup.kibana:
  #host: "https://kibana.yyagi.cloud"
  #username: "beats_admin"
  #password: "L3tM31n!"
#   protocol: "https"
#   ssl.enabled: false
#   ssl.certificate_authorities: ["/usr/share/packetbeat/certs/ca/ca.crt"]
# 
xpack.monitoring.enabled: true
