version: "3.7"

services:
  caddy:
    image: caddy:2.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/caddy:/data
      - /root/caddy/Caddyfile:/etc/caddy/Caddyfile

networks:
  default:
    external:
      name: joystream_default
